dataset_name: default
dataset_path: lfqian/reasoning_path_v2_all
output_type: generate_until
doc_to_target: '{{query}}'
doc_to_text: '{{answer}}'
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{answer}}"
generation_kwargs:
  until:
    - ".........."
  #  - ","
  do_sample: false
  temperature: 0.0
  max_gen_toks: 1024
#filter_list:
#  - name: "score-first"
#    filter:
#      - function: "regex"
#        regex_pattern: "(risefsd|fsafall)"
#      - function: "take_first"
metric_list:
  - metric: exact_match
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: data_filter
tag: v2
test_split: train
training_split: train
