dataset_name: default
dataset_path: TheFinAI/Regulation_XBRL_FinMath_test
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: train
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "</s>"
  temperature: 0.0
  max_gen_toks: 512
metric_list:
  - metric: !function reg_utils.acc
    aggregation: !function reg_utils.acc_agg
    higher_is_better: true
metadata:
  version: '1.0'
task: regXBRL_Math
tag: regulation_XBRL_Math
test_split: test
training_split: train
