dataset_name: default
dataset_path: ChanceFocus/flare-causal20-sc
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "@@"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 512
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
metadata:
  version: '1.0'
task: SC
tag: multifin
test_split: test
