dataset_name: default
dataset_path: TheFinAI/Regulation_XBRL_FinMath_test
output_type: generate_until
doc_to_target: '{{answer}}'
doc_to_text: '{{query}}'
fewshot_split: test
should_decontaminate: true
doc_to_decontamination_query: "{{query}}"
generation_kwargs:
  until:
    - "@@"
  do_sample: false
  temperature: 0.0
  max_gen_toks: 512
metric_list:
  - metric: !function multifin_utils.math_acc
    aggregation: !function multifin_utils.math_acc_agg
    higher_is_better: true
metadata:
  version: '1.0'
task: XBRLMath
tag: multifin
test_split: test
